
spring:
  cloud:
   stream:
      default-binder: kafka
  jpa:
    hibernate:
      ddl-auto: create-drop

ribbon:
  IsSecure: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
server:
  port: 8081
